USE [master]
GO
/****** Object:  Database [DemoTestDB]    Script Date: 23/02/2025 17:19:17 ******/
CREATE DATABASE [DemoTestDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DemoTestDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\DemoTestDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DemoTestDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\DemoTestDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DemoTestDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DemoTestDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DemoTestDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DemoTestDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DemoTestDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DemoTestDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DemoTestDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [DemoTestDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DemoTestDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DemoTestDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DemoTestDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DemoTestDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DemoTestDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DemoTestDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DemoTestDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DemoTestDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DemoTestDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DemoTestDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DemoTestDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DemoTestDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DemoTestDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DemoTestDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DemoTestDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DemoTestDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DemoTestDB] SET RECOVERY FULL 
GO
ALTER DATABASE [DemoTestDB] SET  MULTI_USER 
GO
ALTER DATABASE [DemoTestDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DemoTestDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DemoTestDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DemoTestDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DemoTestDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DemoTestDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DemoTestDB', N'ON'
GO
ALTER DATABASE [DemoTestDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [DemoTestDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [DemoTestDB]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 23/02/2025 17:19:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Description] [nvarchar](1000) NULL,
	[ImageUrl] [varchar](1000) NULL,
	[Notes] [nvarchar](200) NULL,
	[Price] [money] NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 23/02/2025 17:19:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](20) NULL,
	[LastName] [nvarchar](20) NULL,
	[Email] [varchar](50) NOT NULL,
	[Password] [varchar](100) NOT NULL,
	[IsDeleted] [bit] NULL,
	[IsActive] [bit] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Product] ON 

INSERT [dbo].[Product] ([Id], [Name], [Description], [ImageUrl], [Notes], [Price]) VALUES (2, N'Laptop China', N'Hang nhap khau', N'https://surfacecity.vn/wp-content/uploads/L715BL-view-Elite-500x500.jpg', N'hang cu', 2500.0000)
INSERT [dbo].[Product] ([Id], [Name], [Description], [ImageUrl], [Notes], [Price]) VALUES (3, N'Laptop VietNam', N'Hang nhap khau', N'https://surfacecity.vn/wp-content/uploads/L715BL-view-Elite-500x500.jpg', N'hang cu', 2000.0000)
SET IDENTITY_INSERT [dbo].[Product] OFF
GO
SET IDENTITY_INSERT [dbo].[User] ON 

INSERT [dbo].[User] ([Id], [FirstName], [LastName], [Email], [Password], [IsDeleted], [IsActive]) VALUES (1, N'Tri', N'Nguyen', N'tieutri@gmail.com', N'$2a$11$VDEvoXBfTVs91wnp4GyvpO8rENNtsrDMG92aMf78HS3tFTnG/feWi', 0, 1)
INSERT [dbo].[User] ([Id], [FirstName], [LastName], [Email], [Password], [IsDeleted], [IsActive]) VALUES (2, N'Vy', N'Nguyen', N'tringuyen@gmail.com', N'$2a$11$V.zRNNS5NoB.CzYdvzEmq.DvbsdmGdBs8Y96UqV8HHe/2TKTo6ZGa', 0, 1)
INSERT [dbo].[User] ([Id], [FirstName], [LastName], [Email], [Password], [IsDeleted], [IsActive]) VALUES (3, N'Tri1', N'Nguyen', N'tringuyentest@gmail.com', N'$2a$11$cqY1xSHbHTk/BdwCCgNIU.MgVhLgBR3NPtL/9MisbQ58NxpbEB9Rm', 0, 1)
SET IDENTITY_INSERT [dbo].[User] OFF
GO
USE [master]
GO
ALTER DATABASE [DemoTestDB] SET  READ_WRITE 
GO
